title: My Laptop Stands
email: info@mylaptopstands.com
description: >- # this means to ignore newlines until "baseurl:"
  We strive for customer satisfaction and to connect with the right
  product to enhance work productivity, gaming, and leisure while 
  working remotely. A great investment to enhance your productivity.
contacttxt: Contact Us
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mylaptopstands.com/" # the base hostname & protocol for your site, e.g. http://example.com
api_key: ZGIzMTlhNzItMTg1My00MTM5LWI4ZDQtOTM4NDQ5OWEwOWNmNjM3MjMzNTQ0ODY2OTg0ODI3
collections:
  products:
    output: true
 
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
#  - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/